# This workflow installs Python, checks syntax, and runs suma.py
# Ejecuta automáticamente tu script de suma en cada push o pull request

name: Run Python suma.py

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        # Verifica errores de sintaxis o nombres no definidos
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Solo advertencias, no falla el build
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run suma.py
      run: |
        python suma.py
